### PR TITLE
Support IE8. Reduce size of dependencies.

### PR DESCRIPTION
**Pull request by Ender3rd**
I'm working on a project to use this in a site that needs to support IE8. Several of the "utility" imports are causing problems. This provides the same functionality with a smaller footprint.

### CODE REVIEW

**Comment by fengmk2** [comment]
We don't support ie.

**Comment by tparnell8** [comment]
This is quite a small change on your part, and it would at least open the door for people to use this in IE8. 

@fengmk2 is there anyway we can make this change happen?

**Comment by fengmk2** [comment]
iconv-lite support IE?

**Comment by tparnell8** [comment]
It does

**Comment by fengmk2** [comment]
landed 507d2fc60c83cf68362a954bebd19a89b589d704

**Comment by tparnell8** [comment]
@fengmk2 Thank you very much!!!

**Comment by fengmk2** [comment]
release 1.1.0 on nom

**Pull request closed without merging**
